// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/[language]/[...path].tsx';
import * as $1 from './routes/_404.tsx';
import * as $2 from './routes/_500.tsx';
import * as $3 from './routes/_app.tsx';
import * as $4 from './routes/_middleware.ts';
import * as $5 from './routes/api/[language]/paragraph/index.ts';
import * as $6 from './routes/index.tsx';
import * as $$0 from './routes/(_islands)/changelog-trigger.tsx';
import * as $$1 from './routes/(_islands)/changelog.tsx';
import * as $$2 from './routes/(_islands)/citations.tsx';
import * as $$3 from './routes/(_islands)/content-base.tsx';
import * as $$4 from './routes/(_islands)/cross-references.tsx';
import * as $$5 from './routes/(_islands)/menu.tsx';
import * as $$6 from './routes/(_islands)/search.tsx';
import * as $$7 from './routes/(_islands)/trail-hierarchical.tsx';
import * as $$8 from './routes/(_islands)/trail-historical.tsx';

const manifest = {
    routes: {
        './routes/[language]/[...path].tsx': $0,
        './routes/_404.tsx': $1,
        './routes/_500.tsx': $2,
        './routes/_app.tsx': $3,
        './routes/_middleware.ts': $4,
        './routes/api/[language]/paragraph/index.ts': $5,
        './routes/index.tsx': $6,
    },
    islands: {
        './routes/(_islands)/changelog-trigger.tsx': $$0,
        './routes/(_islands)/changelog.tsx': $$1,
        './routes/(_islands)/citations.tsx': $$2,
        './routes/(_islands)/content-base.tsx': $$3,
        './routes/(_islands)/cross-references.tsx': $$4,
        './routes/(_islands)/menu.tsx': $$5,
        './routes/(_islands)/search.tsx': $$6,
        './routes/(_islands)/trail-hierarchical.tsx': $$7,
        './routes/(_islands)/trail-historical.tsx': $$8,
    },
    baseUrl: import.meta.url,
};

export default manifest;
