// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' };
import * as $0 from './routes/index.tsx';
import * as $1 from './routes/read/[...index].tsx';
import * as $$0 from './islands/content.tsx';
import * as $$1 from './islands/menu.tsx';
import * as $$2 from './islands/search.tsx';
import * as $$3 from './islands/trail-hierarchical.tsx';
import * as $$4 from './islands/trail-historical.tsx';

const manifest = {
    routes: {
        './routes/index.tsx': $0,
        './routes/read/[...index].tsx': $1,
    },
    islands: {
        './islands/content.tsx': $$0,
        './islands/menu.tsx': $$1,
        './islands/search.tsx': $$2,
        './islands/trail-hierarchical.tsx': $$3,
        './islands/trail-historical.tsx': $$4,
    },
    baseUrl: import.meta.url,
    config,
};

export default manifest;
