// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_language_path_ from './routes/[language]/[...path].tsx';
import * as $_404 from './routes/_404.tsx';
import * as $_500 from './routes/_500.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $api_language_paragraph_paragraph_number_range_ from './routes/api/[language]/paragraph/[paragraph_number_range].ts';
import * as $index from './routes/index.tsx';
import * as $select_language from './routes/select-language.tsx';
import * as $_islands_changelog_trigger from './routes/(_islands)/changelog-trigger.tsx';
import * as $_islands_changelog from './routes/(_islands)/changelog.tsx';
import * as $_islands_citations from './routes/(_islands)/citations.tsx';
import * as $_islands_content_base from './routes/(_islands)/content-base.tsx';
import * as $_islands_cross_references from './routes/(_islands)/cross-references.tsx';
import * as $_islands_search from './routes/(_islands)/search.tsx';
import * as $_islands_trail_hierarchical from './routes/(_islands)/trail-hierarchical.tsx';
import * as $_islands_trail_historical from './routes/(_islands)/trail-historical.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
    routes: {
        './routes/[language]/[...path].tsx': $_language_path_,
        './routes/_404.tsx': $_404,
        './routes/_500.tsx': $_500,
        './routes/_app.tsx': $_app,
        './routes/_middleware.ts': $_middleware,
        './routes/api/[language]/paragraph/[paragraph_number_range].ts':
            $api_language_paragraph_paragraph_number_range_,
        './routes/index.tsx': $index,
        './routes/select-language.tsx': $select_language,
    },
    islands: {
        './routes/(_islands)/changelog-trigger.tsx': $_islands_changelog_trigger,
        './routes/(_islands)/changelog.tsx': $_islands_changelog,
        './routes/(_islands)/citations.tsx': $_islands_citations,
        './routes/(_islands)/content-base.tsx': $_islands_content_base,
        './routes/(_islands)/cross-references.tsx': $_islands_cross_references,
        './routes/(_islands)/search.tsx': $_islands_search,
        './routes/(_islands)/trail-hierarchical.tsx': $_islands_trail_hierarchical,
        './routes/(_islands)/trail-historical.tsx': $_islands_trail_historical,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
