export enum Content {
    PROLOGUE = 'PROLOGUE',
    PART = 'PART',
    SECTION = 'SECTION',
    CHAPTER = 'CHAPTER',
    ARTICLE = 'ARTICLE',
    ARTICLE_PARAGRAPH = 'ARTICLE_PARAGRAPH',
    SUB_ARTICLE = 'SUB_ARTICLE',
    IN_BRIEF = 'IN_BRIEF',
    PARAGRAPH_GROUP = 'PARAGRAPH_GROUP',

    SPECIAL_1 = 'SPECIAL_1',
    SPECIAL_2 = 'SPECIAL_2',
    SPECIAL_3 = 'SPECIAL_3',

    BLOCK_QUOTE = 'BLOCK_QUOTE',
    PARAGRAPH = 'PARAGRAPH',
    TEXT_CONTAINER = 'TEXT_CONTAINER',
    TEXT = 'TEXT',
}
